name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:

  tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Nimble
      run: nimble install -y nimble contracts nimalyzer

    - name: Debug demo build
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev
        cd demo
        ./build.nims sdl2

    - name: Check with Nimalyzer
      run: |
        sudo apt-get install -y libpcre3
        nimalyzer tools/nimalyzer.cfg
